.TH "SlimeMarkUp.Core/obj/Release/net9.0/.NETCoreApp,Version=v9.0.AssemblyAttributes.cs" 3 "Version 0.1.7.0" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core/obj/Release/net9.0/.NETCoreApp,Version=v9.0.AssemblyAttributes.cs
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
