.TH "SlimeMarkUp.Core/Extensions Directory Reference" 3 "Version 0.1.7.0" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core/Extensions Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBObsidianMarkup\fP"
.br
.ti -1c
.RI "directory \fBSlimeMarkup\fP"
.br
.in -1c
