.TH "SlimeMarkUp.Core/obj/Debug/net10.0 Directory Reference" 3 "Version 0.1.7.0" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core/obj/Debug/net10.0 Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fB\&.NETCoreApp,Version=v10\&.0\&.AssemblyAttributes\&.cs\fP"
.br
.ti -1c
.RI "file \fBSlimeMarkUp\&.Core\&.AssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBSlimeMarkUp\&.Core\&.GlobalUsings\&.g\&.cs\fP"
.br
.in -1c
