.TH "SlimeMarkUp.Core/MarkupParser.cs" 3 "Version 0.1.6.5" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core/MarkupParser.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSlimeMarkUp\&.Core\&.MarkupParser\fP"
.br
.RI "Provides functionality to parse custom markup text into a collection of structured markup elements, supporting extensible block-level parsing via registered markup extensions\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSlimeMarkUp\fP"
.br
.ti -1c
.RI "namespace \fBSlimeMarkUp\&.Core\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
