.TH "SlimeMarkUp.Core/MarkupElement.cs" 3 "Version 0.1.7.0" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core/MarkupElement.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSlimeMarkUp\&.Core\&.MarkupElement\fP"
.br
.RI "Represents an element in a markup structure, including its tag name, content, attributes, and child elements\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSlimeMarkUp\fP"
.br
.ti -1c
.RI "namespace \fBSlimeMarkUp\&.Core\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
