.TH "SlimeMarkUp.Core.Extensions.SlimeMarkup.InlineStyleExtension" 3 "Version 0.1.6.5" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core.Extensions.SlimeMarkup.InlineStyleExtension
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBPriority\fP ()"
.br
.RI "Determines whether the current operation or item has priority status\&. "
.ti -1c
.RI "bool \fBCanParse\fP (string line)"
.br
.RI "Determines whether the specified line can be parsed by the current parser\&. "
.ti -1c
.RI "\fBMarkupElement\fP? \fBParse\fP (string line)"
.br
.RI "Parses the specified line of text and returns a corresponding inline markup element if recognized\&. "
.ti -1c
.RI "IEnumerable< \fBMarkupElement\fP >? \fBParseBlock\fP (Queue< string > lines)"
.br
.in -1c

Public Member Functions inherited from \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP

Public Member Functions inherited from \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCount\fP\fR [get]\fP"
.br
.RI "Gets the number of elements contained in the collection\&. "
.ti -1c
.RI "bool \fBIsToBeProccessed\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether the item is marked to be processed\&. "
.ti -1c
.RI "int \fBOrder\fP\fR [get]\fP"
.br
.RI "Gets the zero-based position of the item within its containing collection or sequence\&. "
.in -1c

Properties inherited from \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.CanParse (string line)"

.PP
Determines whether the specified line can be parsed by the current parser\&. 
.PP
\fBParameters\fP
.RS 4
\fIline\fP The line of text to evaluate for parse compatibility\&. Cannot be null\&.
.RE
.PP
\fBReturns\fP
.RS 4
true if the line can be parsed; otherwise, false\&.
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.SS "\fBMarkupElement\fP? SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.Parse (string line)"

.PP
Parses the specified line of text and returns a corresponding inline markup element if recognized\&. 
.PP
\fBParameters\fP
.RS 4
\fIline\fP The line of text to parse for inline markup\&. Cannot be null\&.
.RE
.PP
\fBReturns\fP
.RS 4
A \fBMarkupElement\fP representing the parsed inline markup element, or \fRnull\fP if the line does not contain a recognized markup element\&.
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB27\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SS "IEnumerable< \fBMarkupElement\fP >? SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.ParseBlock (Queue< string > lines)"

.PP
Implements \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP\&.
.PP
Definition at line \fB37\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.Priority ()"

.PP
Determines whether the current operation or item has priority status\&. 
.PP
\fBReturns\fP
.RS 4
true if the operation or item is considered a priority; otherwise, false\&.
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB19\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.Count\fR [get]\fP"

.PP
Gets the number of elements contained in the collection\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB9\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.IsToBeProccessed\fR [get]\fP"

.PP
Gets a value indicating whether the item is marked to be processed\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB10\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SS "int SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.Order\fR [get]\fP"

.PP
Gets the zero-based position of the item within its containing collection or sequence\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB12\fP of file \fBInlineStyleExtension\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
