.TH "SlimeMarkUp.Core.Models.DocumentProperties" 3 "Version 0.1.6.5" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core.Models.DocumentProperties \- Represents a set of standard metadata properties associated with a document, such as title, author, and publication details\&.  

.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string? \fBFilename\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBTitle\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBAuthor\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBDescription\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBSubject\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBKeywords\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBComments\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBCompany\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBCategory\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBRevisionNumber\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBLanguage\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "List< string >? \fBContributors\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBVersionHistory\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "DateTime? \fBPublished\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents a set of standard metadata properties associated with a document, such as title, author, and publication details\&. 

Use this class to store and access descriptive information about a document, including its filename, subject, keywords, and contributors\&. These properties can be used for indexing, searching, or displaying document information in user interfaces\&. All properties are optional and may be null if not specified\&.
.PP
Definition at line \fB11\fP of file \fBDocumentProperties\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Author\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB17\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Category\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB23\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Comments\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB21\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Company\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "List<string>? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Contributors\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB26\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Description\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB18\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Filename\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB14\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Keywords\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB20\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Language\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB25\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "DateTime? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Published\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB28\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.RevisionNumber\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB24\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Subject\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.Title\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB16\fP of file \fBDocumentProperties\&.cs\fP\&.
.SS "string? SlimeMarkUp\&.Core\&.Models\&.DocumentProperties\&.VersionHistory\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB27\fP of file \fBDocumentProperties\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
