.TH "SlimeMarkUp.Core.Extensions.ObsidianMarkup.ObsidianCodeBlockExtension" 3 "Version 0.1.7.0" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core.Extensions.ObsidianMarkup.ObsidianCodeBlockExtension \- Markup extension that parses fenced code blocks using triple backticks\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanParse\fP (string line)"
.br
.RI "Determines whether the specified line can be parsed as the start of a fenced code block\&. "
.ti -1c
.RI "\fBMarkupElement\fP? \fBParse\fP (string line)"
.br
.RI "Parses a single line\&. "
.ti -1c
.RI "IEnumerable< \fBMarkupElement\fP >? \fBParseBlock\fP (Queue< string > lines)"
.br
.RI "Parses a fenced code block from the provided queue of lines\&. "
.ti -1c
.RI "bool \fBPriority\fP ()"
.br
.RI "Indicates whether this extension has priority over others\&. "
.in -1c

Public Member Functions inherited from \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP

Public Member Functions inherited from \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCount\fP\fR [get]\fP"
.br
.RI "Gets the number of parsed code block elements\&. "
.ti -1c
.RI "bool \fBIsToBeProccessed\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether the block should be processed immediately\&. "
.ti -1c
.RI "int \fBOrder\fP\fR [get]\fP"
.br
.RI "Gets the execution order of the extension\&. "
.in -1c

Properties inherited from \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP
.SH "Detailed Description"
.PP 
Markup extension that parses fenced code blocks using triple backticks\&. 

A code block starts and ends with a line containing exactly \fR```\fP\&. All lines between the opening and closing fences are treated as raw code and preserved without further parsing\&. 
.PP
Definition at line \fB13\fP of file \fBObsidianCodeBlockExtension\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianCodeBlockExtension\&.CanParse (string line)"

.PP
Determines whether the specified line can be parsed as the start of a fenced code block\&. 
.PP
\fBParameters\fP
.RS 4
\fIline\fP The input line\&.
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if the line equals \fR```\fP; otherwise, \fRfalse\fP\&. 
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.SS "\fBMarkupElement\fP? SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianCodeBlockExtension\&.Parse (string line)"

.PP
Parses a single line\&. 
.PP
\fBParameters\fP
.RS 4
\fIline\fP The input line\&.
.RE
.PP
\fBReturns\fP
.RS 4
Always returns \fRnull\fP, since code blocks are parsed as multi-line blocks\&. 
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.SS "IEnumerable< \fBMarkupElement\fP >? SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianCodeBlockExtension\&.ParseBlock (Queue< string > lines)"

.PP
Parses a fenced code block from the provided queue of lines\&. 
.PP
\fBParameters\fP
.RS 4
\fIlines\fP A queue containing the remaining lines of the document\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A collection containing a single \fBMarkupElement\fP with the \fRpre\fP tag and the raw code as content\&. 
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP\&.
.PP
Definition at line \fB52\fP of file \fBObsidianCodeBlockExtension\&.cs\fP\&.
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianCodeBlockExtension\&.Priority ()"

.PP
Indicates whether this extension has priority over others\&. 
.PP
\fBReturns\fP
.RS 4
Always returns \fRfalse\fP\&. 
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB70\fP of file \fBObsidianCodeBlockExtension\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianCodeBlockExtension\&.Count\fR [get]\fP"

.PP
Gets the number of parsed code block elements\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB18\fP of file \fBObsidianCodeBlockExtension\&.cs\fP\&.
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianCodeBlockExtension\&.IsToBeProccessed\fR [get]\fP"

.PP
Gets a value indicating whether the block should be processed immediately\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB32\fP of file \fBObsidianCodeBlockExtension\&.cs\fP\&.
.SS "int SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianCodeBlockExtension\&.Order\fR [get]\fP"

.PP
Gets the execution order of the extension\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB77\fP of file \fBObsidianCodeBlockExtension\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
