.TH "SlimeMarkUp.Core.Extensions.ObsidianMarkup.ObsidianTableExtension" 3 "Version 0.1.7.0" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core.Extensions.ObsidianMarkup.ObsidianTableExtension \- Markup extension that parses Obsidian-style Markdown tables\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBPriority\fP ()"
.br
.RI "Indicates whether this extension has priority over others\&. "
.ti -1c
.RI "bool \fBCanParse\fP (string line)"
.br
.RI "Determines whether the specified line can be parsed as the start of a table\&. "
.ti -1c
.RI "\fBMarkupElement\fP? \fBParse\fP (string line)"
.br
.RI "Parses a single line\&. "
.ti -1c
.RI "IEnumerable< \fBMarkupElement\fP >? \fBParseBlock\fP (Queue< string > lines)"
.br
.RI "Parses a table block from the provided queue of lines\&. "
.in -1c

Public Member Functions inherited from \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP

Public Member Functions inherited from \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsToBeProccessed\fP\fR [get]\fP"
.br
.RI "Gets a value indicating whether the block should be processed immediately\&. "
.ti -1c
.RI "int \fBOrder\fP\fR [get]\fP"
.br
.RI "Gets the execution order of the extension\&. "
.ti -1c
.RI "int \fBCount\fP\fR [get]\fP"
.br
.RI "Gets the number of parsed table elements\&. "
.in -1c

Properties inherited from \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP
.SH "Detailed Description"
.PP 
Markup extension that parses Obsidian-style Markdown tables\&. 

Supported syntax: 
.PP
.nf
<table class="markdownTable">
  <tr class="markdownTableHead">    <th class="markdownTableHeadNone"> Name  </th>    <th class="markdownTableHeadNone"> Age  </th>    <th class="markdownTableHeadNone"> City  </th>  </tr>
<tr class="markdownTableRowOdd">    <td class="markdownTableBodyNone"> John  </td>    <td class="markdownTableBodyNone"> 30  </td>    <td class="markdownTableBodyNone"> Rome  </td>  </tr>
<tr class="markdownTableRowEven">    <td class="markdownTableBodyNone"> Anna  </td>    <td class="markdownTableBodyNone"> 25  </td>    <td class="markdownTableBodyNone"> Paris  </td>  </tr></table>

.fi
.PP
 

.PP
Lines starting with \fR|\fP are treated as table rows\&. Separator rows containing only \fR-\fP or \fR=\fP characters are ignored\&. 
.PP
Definition at line \fB23\fP of file \fBObsidianTableExtension\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianTableExtension\&.CanParse (string line)"

.PP
Determines whether the specified line can be parsed as the start of a table\&. 
.PP
\fBParameters\fP
.RS 4
\fIline\fP The input line\&.
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if the line starts with \fR|\fP; otherwise, \fRfalse\fP\&. 
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.SS "\fBMarkupElement\fP? SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianTableExtension\&.Parse (string line)"

.PP
Parses a single line\&. 
.PP
\fBParameters\fP
.RS 4
\fIline\fP The input line\&.
.RE
.PP
\fBReturns\fP
.RS 4
Always returns \fRnull\fP, since tables are parsed as block elements\&. 
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.SS "IEnumerable< \fBMarkupElement\fP >? SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianTableExtension\&.ParseBlock (Queue< string > lines)"

.PP
Parses a table block from the provided queue of lines\&. 
.PP
\fBParameters\fP
.RS 4
\fIlines\fP A queue containing the remaining lines of the document\&. 
.RE
.PP
\fBReturns\fP
.RS 4
A collection containing a single \fBMarkupElement\fP with the \fRtable\fP tag and its rows as content\&. 
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP\&.
.PP
Definition at line \fB82\fP of file \fBObsidianTableExtension\&.cs\fP\&.
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianTableExtension\&.Priority ()"

.PP
Indicates whether this extension has priority over others\&. 
.PP
\fBReturns\fP
.RS 4
Always returns \fRfalse\fP\&. 
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB51\fP of file \fBObsidianTableExtension\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianTableExtension\&.Count\fR [get]\fP"

.PP
Gets the number of parsed table elements\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB44\fP of file \fBObsidianTableExtension\&.cs\fP\&.
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianTableExtension\&.IsToBeProccessed\fR [get]\fP"

.PP
Gets a value indicating whether the block should be processed immediately\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB29\fP of file \fBObsidianTableExtension\&.cs\fP\&.
.SS "int SlimeMarkUp\&.Core\&.Extensions\&.ObsidianMarkup\&.ObsidianTableExtension\&.Order\fR [get]\fP"

.PP
Gets the execution order of the extension\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB34\fP of file \fBObsidianTableExtension\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
