.TH "SlimeMarkUp.Core.Extensions.ObsidianMarkup" 3 "Version 0.1.7.0" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core.Extensions.ObsidianMarkup
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBObsidianBlockquoteExtension\fP"
.br
.RI "Markup extension that parses Obsidian-style blockquotes\&. "
.ti -1c
.RI "class \fBObsidianCodeBlockExtension\fP"
.br
.RI "Markup extension that parses fenced code blocks using triple backticks\&. "
.ti -1c
.RI "class \fBObsidianHeaderExtension\fP"
.br
.RI "Markup extension that parses Obsidian-style Markdown headers\&. "
.ti -1c
.RI "class \fBObsidianImageExtension\fP"
.br
.RI "Markup extension that parses Obsidian-style Markdown image syntax\&. "
.ti -1c
.RI "class \fBObsidianInlineStyleExtension\fP"
.br
.RI "Markup extension that parses inline text styles such as bold and italic\&. "
.ti -1c
.RI "class \fBObsidianLinkExtension\fP"
.br
.RI "Markup extension that parses Obsidian-style Markdown links\&. "
.ti -1c
.RI "class \fBObsidianListExtension\fP"
.br
.RI "Markup extension that parses unordered lists using dash-prefixed items\&. "
.ti -1c
.RI "class \fBObsidianTableExtension\fP"
.br
.RI "Markup extension that parses Obsidian-style Markdown tables\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
