.TH "SlimeMarkUp.Core.HtmlRenderer" 3 "Version 0.1.6.5" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core.HtmlRenderer \- Provides functionality to render a collection of markup elements into an HTML string\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBRender\fP (IEnumerable< \fBMarkupElement\fP > elements)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides functionality to render a collection of markup elements into an HTML string\&. 

Use this class to convert a sequence of markup elements, such as images, tables, and headings, into their corresponding HTML representation\&. The renderer handles specific tags with custom logic and wraps other elements in their respective HTML tags\&. This class is not thread-safe; create a separate instance for concurrent rendering operations\&.
.PP
Definition at line \fB15\fP of file \fBHtmlRenderer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string SlimeMarkUp\&.Core\&.HtmlRenderer\&.Render (IEnumerable< \fBMarkupElement\fP > elements)"

.PP
Definition at line \fB17\fP of file \fBHtmlRenderer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
