.TH "SlimeMarkUp.Core.Models" 3 "Version 0.1.6.5" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDocumentProperties\fP"
.br
.RI "Represents a set of standard metadata properties associated with a document, such as title, author, and publication details\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
