.TH "SlimeMarkUp.Core.Extensions.SlimeMarkup.InlineStyleExtension" 3 "Version 0.1.7.0" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core.Extensions.SlimeMarkup.InlineStyleExtension \- A markup extension that parses inline style elements in a line of text and converts them to HTML-like tags\&. Supports bold (\fBtext\fP), italic (\fItext\fP), strikethrough (text), and underline (++text++)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBPriority\fP ()"
.br
.RI "Determines whether this extension has priority over others\&. Always returns \fRfalse\fP\&. "
.ti -1c
.RI "bool \fBCanParse\fP (string line)"
.br
.RI "Determines if a line of text can be parsed by this extension\&. Lines containing **, *, ~~, or ++ are considered parseable, unless they start with a backslash (), which escapes formatting\&. "
.ti -1c
.RI "\fBMarkupElement\fP? \fBParse\fP (string line)"
.br
.RI "Parses a single line of text and applies inline styles\&. Wraps the resulting content in a \fRp\fP tag\&. "
.ti -1c
.RI "IEnumerable< \fBMarkupElement\fP >? \fBParseBlock\fP (Queue< string > lines)"
.br
.RI "Parses a block of lines from a queue, applying inline styles to the first line if it is parseable\&. "
.in -1c

Public Member Functions inherited from \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP

Public Member Functions inherited from \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCount\fP\fR [get]\fP"
.br
.RI "Gets the number of inline styles detected or applied\&. Currently always returns 0 because counting is not implemented\&. "
.ti -1c
.RI "bool \fBIsToBeProccessed\fP\fR [get]\fP"
.br
.RI "Indicates whether this extension should be processed\&. Always returns \fRfalse\fP as processing is handled manually\&. "
.ti -1c
.RI "int \fBOrder\fP\fR [get]\fP"
.br
.RI "Gets the order in which this extension should be applied relative to others\&. Lower numbers are processed earlier\&. This extension has an order of 2\&. "
.in -1c

Properties inherited from \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP
.SH "Detailed Description"
.PP 
A markup extension that parses inline style elements in a line of text and converts them to HTML-like tags\&. Supports bold (\fBtext\fP), italic (\fItext\fP), strikethrough (text), and underline (++text++)\&. 
.PP
Definition at line \fB11\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.CanParse (string line)"

.PP
Determines if a line of text can be parsed by this extension\&. Lines containing **, *, ~~, or ++ are considered parseable, unless they start with a backslash (), which escapes formatting\&. 
.PP
\fBParameters\fP
.RS 4
\fIline\fP The input line to check\&.
.RE
.PP
\fBReturns\fP
.RS 4
\fRtrue\fP if the line contains inline style syntax and is not escaped; otherwise, \fRfalse\fP\&.
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.SS "\fBMarkupElement\fP? SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.Parse (string line)"

.PP
Parses a single line of text and applies inline styles\&. Wraps the resulting content in a \fRp\fP tag\&. 
.PP
\fBParameters\fP
.RS 4
\fIline\fP The line of text to parse\&.
.RE
.PP
\fBReturns\fP
.RS 4
A \fBMarkupElement\fP containing the styled content\&.
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB62\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SS "IEnumerable< \fBMarkupElement\fP >? SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.ParseBlock (Queue< string > lines)"

.PP
Parses a block of lines from a queue, applying inline styles to the first line if it is parseable\&. 
.PP
\fBParameters\fP
.RS 4
\fIlines\fP A queue of lines to parse\&.
.RE
.PP
\fBReturns\fP
.RS 4
An enumerable containing a single \fBMarkupElement\fP with styled content, or \fRnull\fP if no lines can be parsed\&.
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IBlockMarkupExtension\fP\&.
.PP
Definition at line \fB77\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.Priority ()"

.PP
Determines whether this extension has priority over others\&. Always returns \fRfalse\fP\&. 
.PP
\fBReturns\fP
.RS 4
\fRfalse\fP
.RE
.PP

.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB40\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.Count\fR [get]\fP"

.PP
Gets the number of inline styles detected or applied\&. Currently always returns 0 because counting is not implemented\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB17\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SS "bool SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.IsToBeProccessed\fR [get]\fP"

.PP
Indicates whether this extension should be processed\&. Always returns \fRfalse\fP as processing is handled manually\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB22\fP of file \fBInlineStyleExtension\&.cs\fP\&.
.SS "int SlimeMarkUp\&.Core\&.Extensions\&.SlimeMarkup\&.InlineStyleExtension\&.Order\fR [get]\fP"

.PP
Gets the order in which this extension should be applied relative to others\&. Lower numbers are processed earlier\&. This extension has an order of 2\&. 
.PP
Implements \fBSlimeMarkUp\&.Core\&.IMarkupExtension\fP\&.
.PP
Definition at line \fB28\fP of file \fBInlineStyleExtension\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
