.TH "SlimeMarkUp.Core.Extensions.SlimeMarkup" 3 "Version 0.1.6.5" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeMarkUp.Core.Extensions.SlimeMarkup
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBlockquoteExtension\fP"
.br
.ti -1c
.RI "class \fBCodeBlockExtension\fP"
.br
.ti -1c
.RI "class \fBEscapeCharsExtension\fP"
.br
.ti -1c
.RI "class \fBHeaderExtension\fP"
.br
.ti -1c
.RI "class \fBHorizontalRuleExtension\fP"
.br
.RI "Provides an extension for parsing blockquote-style horizontal rules in markup content\&. "
.ti -1c
.RI "class \fBImageExtension\fP"
.br
.ti -1c
.RI "class \fBIncludeCSSExtension\fP"
.br
.ti -1c
.RI "class \fBIncludeExtension\fP"
.br
.ti -1c
.RI "class \fBIncludeScriptExtension\fP"
.br
.ti -1c
.RI "class \fBInlineStyleExtension\fP"
.br
.ti -1c
.RI "class \fBLinkExtension\fP"
.br
.ti -1c
.RI "class \fBListExtension\fP"
.br
.ti -1c
.RI "class \fBTableExtension\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
