.TH "SlimeExtensiveMarkDown.Core" 3 "Version 0.1.7.0" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeExtensiveMarkDown.Core
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIMarkupExtension\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
