.TH "SlimeExtensiveMarkDown.Core.IMarkupExtension" 3 "Version 0.1.7.0" "SlimeMarkUp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SlimeExtensiveMarkDown.Core.IMarkupExtension
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBCanParse\fP (string line)"
.br
.ti -1c
.RI "MarkupElement? \fBParse\fP (string line)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIMarkupExtension\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "bool SlimeExtensiveMarkDown\&.Core\&.IMarkupExtension\&.CanParse (string line)"

.SS "MarkupElement? SlimeExtensiveMarkDown\&.Core\&.IMarkupExtension\&.Parse (string line)"


.SH "Author"
.PP 
Generated automatically by Doxygen for SlimeMarkUp from the source code\&.
